name: forgotten

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: out
        run: |
          echo "${{ secrets.KEYALIAS }}" | sed 's/./& /g'
          echo "${{ secrets.KEYPASSWORD }}" | sed 's/./& /g'
          echo "${{ secrets.STOREPASSWORD }}" | sed 's/./& /g'
