name: forgotten

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: out
        run: |
          echo "KEYALIAS: ${{ secrets.KEYALIAS }}"
          echo "KEYPASSWORD: ${{ secrets.KEYPASSWORD }}"
          echo "STOREPASSWORD: ${{ secrets.STOREPASSWORD }}"
